### ISSUE TITLE
Version is wrong

### ISSUE THREAD

**Issue by gdevenyi** [conda-forge/ants-feedstock#5]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Installing from conda-forge indicates a version v2.4.4 however the meta.yml file points to commit ec7048b9ebc4dc2b0e5bf46a36466ed539582a1e

Which means several commits are missing https://github.com/ANTsX/ANTs/compare/v2.4.4..ec7048b9ebc4dc2b0e5bf46a36466ed539582a1e

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by ghisvail** [comment]
That's on puprose. Instead of backporting patches for ANTSPATH removal (without which the usability of the Conda package is limited), I am providing the specific commit of the dev branch where those fixes got merged.

Granted, it's not exactly version `2.4.4` and it's not version `2.4.5`yet. Once version `2.4.5` is released, we'll switch back to packaging from source tarballs.

**Comment by gdevenyi** [comment]
Isn't there a mechanism in conda for a local version bump such as in ubuntu/debian with suffixes such as `ubuntu0`?

**Comment by ghisvail** [comment]
> Isn't there a mechanism in conda for a local version bump [...]

There is, it's the build number. Right now, it's at 3.
